Homework 8.02 part2
sotickmars/TeachMeRepository pull request #2
Opened 2020-02-10 23:53 UTC by sotickmars

Доработал до конца задание с flex и float.

Сделал фон с картинкой и наверх наложил opacity другим блоком ( через псевдокласс не мог понять почему не вышло..., точнее выходило - но если только применять position.... но этого делать не хотелось).

2020-02-11 06:14 UTC, tpotapchik requested changes

2020-02-11 06:14 UTC, tpotapchik commented on project/homework/assets/styles/main.css
> +.inner-menu li:nth-of-type(n+4) {
it's worth using more simple selectors

2020-02-11 06:14 UTC, tpotapchik commented on project/homework/assets/styles/main.css
> +
empty line

2020-02-11 06:14 UTC, tpotapchik commented on project/homework/assets/styles/main.css
> +	background: url(../images/opo.jpg) no-repeat;
`opo.jpg`?

2020-02-11 06:14 UTC, tpotapchik commented on project/homework/assets/styles/main.css
> +	background: rgb(0, 0, 0);
black or #000

2020-02-11 06:14 UTC, tpotapchik commented on project/homework/index.html
> +			<ul class="menu basic">
https://take.ms/yEZmN

2020-02-11 06:14 UTC, tpotapchik commented on project/homework/assets/styles/main.css
> +	height: 300px;
no height value

2020-02-11 10:11 UTC, sotickmars commented on project/homework/index.html
> +			<ul class="menu basic">
но могу делать через UL?

2020-02-11 11:22 UTC, sotickmars commented on project/homework/index.html
> +			<ul class="menu basic">
тогда просто выходит поменьше html структура

2020-02-13 06:38 UTC, tpotapchik requested changes

2020-02-13 06:38 UTC, tpotapchik commented on project/homework/assets/css/main.css
> +	font-size: 48px;
please add line-height

2020-02-13 06:38 UTC, tpotapchik commented on project/homework/assets/css/main.css
> +.pricing::after {
almost the same as `.title-awesome::after`

2020-02-13 06:38 UTC, tpotapchik commented on project/homework/assets/css/main.css
> +
empty line

2020-02-13 06:38 UTC, tpotapchik commented on project/homework/assets/css/main.css
> +.paragraph-conteiner {
what's the word `conteiner`

2020-02-13 06:38 UTC, tpotapchik commented on project/homework/assets/css/main.css
> +	display: flex;
?

2020-02-13 06:38 UTC, tpotapchik commented on project/homework/assets/css/main.css
> +}
please add line

2020-02-13 06:38 UTC, tpotapchik commented on project/homework/assets/css/main.css
> +.stylish:after {
see the comment above

2020-02-13 06:38 UTC, tpotapchik commented on project/homework/assets/css/main.css
> +	display: flex;
no flex here

2020-02-13 06:38 UTC, tpotapchik commented on project/homework/index.html
> +							<li>5 gb of space</li>
in html not a good way to format the code. usually it's 4 spaces

2020-02-13 11:40 UTC, merged